name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run script
        run: |
          echo "Running CI..."
          type app.txt

      - name: Done
        run: echo "CI finished"