name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run build
        run: |
          echo "Running CI..."
          cat app.txt

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy step
        run: |
          echo "Deploying app..."
          echo "App deployed successfully 🚀"